### ISSUE TITLE
How to subscribe to a location of the user in flutter

### ISSUE THREAD

**Issue by Ilthizam** [roam-ai/roam-flutter#19]
I have used roam's `roam.startTracking()` to start tracking. I want to know how to subscribe to this location and show the location data in another flutter application.   I have tried roam.subscribeUserLocation("userId"), but it returns a bool. 

How can I achieve this task of getting the location from one device and showing geo coordinates of that user, on another device in Flutter SDK?

**Comment by jothipriyadharshanr** [comment]
Hey @Ilthizam Once the user if subscribed with the method `Roam.subscribeUserLocation("userId")`, you can listen to location from Native side of our SDK which is currently supported. Our scheduled release planned for tomorrow has direct method which will have the support to listen to these locations from the flutter side itself instead of native side. 

We will update the version here once the release is live.
